on: [push, pull_request]
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        otp: [21.3, 22.2]
        elixir: [1.9.4, 1.10.0]

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Cache dialyzer plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-plts

      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Deps get
        run: mix deps.get

      - name: Check Credo
        run: mix credo

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Tests
        run: mix do compile --warnings-as-errors, coveralls.json, test

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./codecov.yml
          file: ./cover/excoveralls.json

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
